"""Agent state representation for multi-turn sessions and decision tracking."""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from src.core.models import DecisionState
from src.knowledge.evidence import EvidencePack
from src.llm.models import GeneratedResponse
from src.tools.order_models import CustomerSafeOrder


class RouteType(str, Enum):
    """Routing classification for incoming queries."""

    KNOWLEDGE = "KNOWLEDGE"
    ORDER = "ORDER"
    CLARIFY = "CLARIFY"
    UNSUPPORTED = "UNSUPPORTED"


class OrderIntent(str, Enum):
    """Specific order-related intents."""

    STATUS = "STATUS"
    SHIPPING_TRACKING = "SHIPPING_TRACKING"
    CANCELLATION = "CANCELLATION"
    RETURN_REFUND = "RETURN_REFUND"
    DAMAGE_EXCEPTION = "DAMAGE_EXCEPTION"
    GENERAL = "GENERAL"


class AgentDecision(BaseModel):
    """Deterministic decision generated by the decision engine."""

    state: DecisionState = Field(..., description="Decision state enum")
    reason: str = Field(..., description="Deterministic reason for this decision")
    handoff_recommended: bool = Field(
        default=False, description="Whether human support assistance is recommended"
    )
    handoff_reason: Optional[str] = Field(
        default=None, description="Detailed explanation if handoff is recommended"
    )
    suggested_clarification: Optional[str] = Field(
        default=None, description="Suggested question to ask user if state is CLARIFY"
    )
    supported_action: Optional[str] = Field(
        default=None,
        description="Explicit read-only action performed (e.g. 'order_lookup'). Never a mutation.",
    )


class AgentState(BaseModel):
    """State of a single conversation turn."""

    session_id: str = Field(..., description="Unique session ID")
    turn_id: int = Field(default=1, description="1-indexed turn number in session")
    raw_query: str = Field(..., description="Original user message")
    normalized_query: str = Field(..., description="Cleaned and normalized query")

    # Routing & Entity resolution
    route: RouteType = Field(..., description="Detected route classification")
    order_intent: Optional[OrderIntent] = Field(
        default=None, description="Specific order intent if route is ORDER"
    )
    extracted_order_id: Optional[str] = Field(
        default=None, description="Order ID explicitly found in current turn"
    )
    active_order_id: Optional[str] = Field(
        default=None, description="Active order ID resolved from turn or session history"
    )
    active_topic: Optional[str] = Field(
        default=None, description="Active policy topic or context"
    )

    # Evidence & Tool results
    evidence_pack: Optional[EvidencePack] = Field(
        default=None, description="Authoritative resolved knowledge evidence"
    )
    customer_safe_order: Optional[CustomerSafeOrder] = Field(
        default=None, description="Sanitized and reconciled customer-safe order"
    )

    # Decision outcome
    decision: Optional[AgentDecision] = Field(
        default=None, description="Decision produced by the decision engine"
    )
    handoff_recommended: bool = Field(
        default=False, description="Top-level handoff recommendation flag"
    )
    handoff_reason: Optional[str] = Field(
        default=None, description="Top-level handoff reason if applicable"
    )

    # Final Grounded Response
    response: Optional[GeneratedResponse] = Field(
        default=None, description="Validated customer-facing response"
    )

    # Observability trace
    trace: Dict[str, Any] = Field(
        default_factory=dict, description="Structured audit trace for observability"
    )
