"""Agent state representation for multi-turn sessions and decision tracking."""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from src.core.models import DecisionState
from src.knowledge.evidence import EvidencePack
from src.llm.models import GeneratedResponse
from src.tools.order_models import CustomerSafeOrder


class RouteType(str, Enum):
    """Routing classification for incoming queries."""

    KNOWLEDGE = "KNOWLEDGE"
    ORDER = "ORDER"
    CLARIFY = "CLARIFY"
    UNSUPPORTED = "UNSUPPORTED"


class OrderIntent(str, Enum):
    """Specific order-related intents."""

    STATUS = "STATUS"
    SHIPPING_TRACKING = "SHIPPING_TRACKING"
    CANCELLATION = "CANCELLATION"
    RETURN_REFUND = "RETURN_REFUND"
    DAMAGE_EXCEPTION = "DAMAGE_EXCEPTION"
    GENERAL = "GENERAL"


class AgentDecision(BaseModel):
    """Deterministic decision generated by the decision engine."""

    state: DecisionState = Field(..., description="Decision state enum")
    reason: str = Field(..., description="Deterministic reason for this decision")
    handoff_recommended: bool = Field(
        default=False, description="Whether human support assistance is recommended"
    )
    handoff_reason: Optional[str] = Field(
        default=None, description="Detailed explanation if handoff is recommended"
    )
    suggested_clarification: Optional[str] = Field(
        default=None, description="Suggested question to ask user if state is CLARIFY"
    )
    supported_action: Optional[str] = Field(
        default=None,
        description="Explicit read-only action performed (e.g. 'order_lookup'). Never a mutation.",
    )


class PublicAgentResponse(BaseModel):
    """Clean public customer-facing response contract."""

    session_id: str = Field(..., description="Unique session ID")
    turn_id: int = Field(..., description="1-indexed turn ID in session")
    message: str = Field(..., description="Customer response message")
    decision_state: DecisionState = Field(..., description="Deterministic decision state")
    citations: List[str] = Field(default_factory=list, description="Validated citations formatted [doc > heading]")
    handoff_recommended: bool = Field(default=False, description="Whether human support is recommended")
    handoff_reason: Optional[str] = Field(default=None, description="Human handoff reason if applicable")
    supported_action: Optional[str] = Field(default=None, description="Read-only action performed if any")
    is_fallback: bool = Field(default=False, description="True if response was produced by deterministic fallback")
    fallback_reason: Optional[str] = Field(default=None, description="Reason why fallback was triggered")


class AgentState(BaseModel):
    """State of a single conversation turn."""

    session_id: str = Field(..., description="Unique session ID")
    turn_id: int = Field(default=1, description="1-indexed turn number in session")
    raw_query: str = Field(..., description="Original user message")
    normalized_query: str = Field(..., description="Cleaned and normalized query")

    # Routing & Entity resolution
    route: RouteType = Field(..., description="Detected route classification")
    order_intent: Optional[OrderIntent] = Field(
        default=None, description="Specific order intent if route is ORDER"
    )
    extracted_order_id: Optional[str] = Field(
        default=None, description="Order ID explicitly found in current turn"
    )
    active_order_id: Optional[str] = Field(
        default=None, description="Active order ID resolved from turn or session history"
    )
    active_topic: Optional[str] = Field(
        default=None, description="Active policy topic or context"
    )

    # Evidence & Tool results
    evidence_pack: Optional[EvidencePack] = Field(
        default=None, description="Authoritative resolved knowledge evidence"
    )
    customer_safe_order: Optional[CustomerSafeOrder] = Field(
        default=None, description="Sanitized and reconciled customer-safe order"
    )

    # Decision outcome
    decision: Optional[AgentDecision] = Field(
        default=None, description="Decision produced by the decision engine"
    )
    handoff_recommended: bool = Field(
        default=False, description="Top-level handoff recommendation flag"
    )
    handoff_reason: Optional[str] = Field(
        default=None, description="Top-level handoff reason if applicable"
    )

    # Final Grounded Response
    response: Optional[GeneratedResponse] = Field(
        default=None, description="Validated customer-facing response"
    )

    # Observability trace
    trace: Dict[str, Any] = Field(
        default_factory=dict, description="Structured audit trace for observability"
    )

    @property
    def response_message(self) -> str:
        """Return final validated message string."""
        return self.response.message if self.response else ""

    @property
    def citation_strings(self) -> List[str]:
        """Return list of citation strings."""
        return self.response.citation_strings if self.response else []

    @property
    def is_fallback(self) -> bool:
        """Return whether response was generated via deterministic fallback."""
        return self.response.is_fallback if self.response else False

    def to_public_response(self) -> PublicAgentResponse:
        """Produce clean public response object without exposing internal models."""
        return PublicAgentResponse(
            session_id=self.session_id,
            turn_id=self.turn_id,
            message=self.response_message,
            decision_state=self.decision.state if self.decision else DecisionState.HANDOFF,
            citations=self.citation_strings,
            handoff_recommended=self.handoff_recommended,
            handoff_reason=self.handoff_reason,
            supported_action=self.response.supported_action if self.response else None,
            is_fallback=self.is_fallback,
            fallback_reason=self.response.fallback_reason if self.response else None,
        )
